# Generated by Django 3.1.6 on 2021-02-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=156)),
            ],
        ),
        migrations.DeleteModel(
            name='lang',
        ),
        migrations.AddField(
            model_name='entry',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.language', verbose_name=''),
        ),
    ]
